/** Every label of the administration space, in one greppable place. */
export const ADMIN_CONTENT = {
  roleLabel: 'Administration',
  nav: {
    group: 'Pilotage',
    overview: 'Tableau de bord',
    applications: 'Demandes partenaires',
    allocations: 'Abondements',
    accounts: 'Comptes',
    payments: 'Transactions',
  },
  applications: {
    title: 'Demandes d’inscription',
    subtitle:
      'Chaque demande est examinée par un agent. La décision est motivée, horodatée et conservée : elle ne peut pas être reprise.',
    empty: 'Aucune demande dans cet état.',
    loadMore: 'Charger plus',
    loading: 'Chargement…',
    filedOn: 'Déposée le',
    siren: 'SIREN',
    review: 'Examiner',
    viewDecision: 'Voir la décision',
    status: {
      pending: 'En attente',
      active: 'Acceptée',
      refused: 'Refusée',
      banned: 'Suspendue',
    },
    filter: {
      label: 'Filtrer par état',
      pending: 'En attente',
      active: 'Acceptées',
      refused: 'Refusées',
    },
  },
  application: {
    trail: 'Demande',
    back: 'Retour aux demandes',
    legalName: 'Raison sociale',
    tradeName: 'Enseigne',
    siren: 'SIREN',
    businessPurpose: 'Objet social',
    address: 'Adresse',
    categories: 'Catégories',
    owner: 'Compte demandeur',
    filedOn: 'Déposée le',
    decidedOn: 'Décidée le',
    decision: {
      title: 'Décision',
      help: 'Le motif est conservé et opposable. Il est communiqué au partenaire.',
      reasonLabel: 'Motif de la décision',
      reasonPlaceholder:
        'SIREN vérifié, objet social conforme à la catégorie déclarée…',
      approve: 'Accepter',
      refuse: 'Refuser',
      submitting: 'Enregistrement…',
      approved: 'Demande acceptée. Le partenaire est actif.',
      refused: 'Demande refusée. Le motif a été enregistré.',
      reasonRequired:
        'Un motif est obligatoire, y compris pour une acceptation.',
    },
    settled: {
      title: 'Demande déjà traitée',
      body: 'Cette demande a reçu une décision. Une décision ne se reprend pas : elle se corrige par une nouvelle demande.',
    },
  },
  allocations: {
    title: 'Abondements',
    subtitle:
      'Créditez les portefeuilles d’un employeur. Un versement est définitif et ne se rejoue pas.',
    trail: 'Abondement',
    empty: 'Aucun abondement pour le moment.',
    createTitle: 'Nouvel abondement',
    employerLabel: 'Employeur',
    employerPlaceholder: 'Choisissez un employeur',
    labelLabel: 'Libellé',
    labelPlaceholder: 'Abondement de septembre',
    amountLabel: 'Montant par salarié',
    amountHelp: 'En euros. Chaque portefeuille actif recevra ce montant.',
    create: 'Créer',
    creating: 'Création…',
    createdOn: 'Créé le',
    perEmployee: 'par salarié',
    wallets: (count: number) =>
      count === 1 ? '1 portefeuille actif' : `${count} portefeuilles actifs`,
    status: {
      draft: 'À verser',
      applied: 'Versé',
    },
    open: 'Ouvrir',
    employerRequired: 'Choisissez un employeur.',
    labelRequired: 'Donnez un libellé à cet abondement.',
    amountRequired: 'Saisissez un montant supérieur à zéro.',
  },
  allocation: {
    back: 'Retour aux abondements',
    employer: 'Employeur',
    label: 'Libellé',
    amount: 'Montant par salarié',
    total: 'Total à verser',
    beneficiaries: 'Portefeuilles crédités',
    excluded: 'Portefeuilles ignorés',
    excludedReason: {
      wallet_disabled: 'Portefeuille désactivé',
    },
    noExcluded: 'Aucun portefeuille ignoré.',
    apply: 'Verser maintenant',
    applying: 'Versement…',
    applyHelp:
      'Le versement crédite chaque portefeuille actif. Il écrit des écritures immuables et ne peut pas être annulé.',
    appliedToast: 'Abondement versé.',
    settled: {
      title: 'Abondement déjà versé',
      body: 'Les écritures qu’il a produites sont définitives. Pour créditer à nouveau, créez un autre abondement.',
    },
  },
  accounts: {
    title: 'Comptes',
    subtitle:
      'Tous les comptes du dispositif. Une suspension ou une clôture prend effet tout de suite : la personne est déconnectée.',
    searchLabel: 'Rechercher un compte par adresse e-mail',
    searchPlaceholder: 'nom@domaine.fr',
    search: 'Rechercher',
    roleFilter: 'Filtrer par profil',
    allRoles: 'Tous',
    roles: {
      employee: 'Salarié·e',
      partner: 'Partenaire',
      admin: 'Administration',
    },
    unknownRole: 'Sans profil',
    status: {
      active: 'Actif',
      suspended: 'Suspendu',
      closed: 'Clôturé',
    },
    createdOn: 'Créé le',
    open: 'Gérer',
    empty: 'Aucun compte ne correspond à cette recherche.',
    total: (count: number) => (count === 1 ? '1 compte' : `${count} comptes`),
    pagination: 'Pages de la liste des comptes',
    previous: 'Précédent',
    next: 'Suivant',
    pageOf: (page: number, count: number) => `Page ${page} sur ${count}`,
  },
  account: {
    trail: 'Compte',
    back: 'Retour aux comptes',
    role: 'Profil',
    status: 'Statut',
    until: (date: string) => `jusqu’au ${date}`,
    createdOn: 'Créé le',
    reason: 'Motif',
    self: 'C’est votre propre compte : il ne peut être ni suspendu ni clôturé depuis cet écran.',
    change: {
      title: 'Changer le statut',
      measureLabel: 'Mesure à prendre',
      suspend: 'Suspendre',
      close: 'Clôturer',
      duration: 'Durée de la suspension',
      days: (days: number) => `${days} jours`,
      reasonLabel: 'Motif',
      reasonHint: 'Conservé avec le compte tant que la mesure dure.',
      reasonRequired: 'Un motif est obligatoire.',
      suspendWarning:
        'La personne est déconnectée tout de suite et ne peut plus se connecter avant la fin de la suspension.',
      closeWarning:
        'La clôture n’a pas de fin : la personne est déconnectée et ne peut plus se connecter. Rien n’est effacé, ses opérations restent.',
      submitSuspend: 'Suspendre le compte',
      submitClose: 'Clôturer le compte',
      submitting: 'Enregistrement…',
      suspended: 'Compte suspendu. Ses sessions ont été fermées.',
      closed: 'Compte clôturé. Ses sessions ont été fermées.',
      failed: 'Le statut n’a pas pu être changé. Réessayez.',
    },
    reactivate: {
      title: 'Réactiver le compte',
      body: 'Le compte peut se reconnecter tout de suite. Le motif de la mesure est retiré du compte.',
      submit: 'Réactiver',
      done: 'Compte réactivé.',
    },
  },
  payments: {
    title: 'Transactions',
    subtitle: 'Toutes les transactions du dispositif, validées ou refusées.',
    export: {
      title: 'Export CSV',
      body: 'Une ligne par transaction : identifiant, date, salarié, partenaire, montant en centimes et état. Le fichier est produit par le serveur au moment du téléchargement.',
      download: 'Télécharger transactions.csv',
    },
  },
  error: {
    title: 'Cette page n’a pas pu être affichée.',
    body: 'Une erreur est survenue. Vous pouvez réessayer.',
  },
} as const;
