name: Mirror

on:
  push:
    branches: [main]

env:
  REPOSITORY_URL: git@github.com:EpitechPGE3-2026/G-SVR-500-NAN-5-1-survivor-3.git

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prerequisites:
    name: 'Prerequisites'
    runs-on: ubuntu-latest
    outputs:
      is_mirror_repository: ${{ steps.mirror_repository_check.outputs.is_mirror }}
    steps:
      - name: 'Check repository url'
        id: mirror_repository_check
        run: |
          MIRROR_REPOSITORY=$(echo '${{ env.REPOSITORY_URL }}' | sed -e 's/:/\//' -e 's/@/:\/\//')
          if [ "$MIRROR_REPOSITORY" = '${{ github.repositoryUrl }}' ]
          then
            echo "is_mirror=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_mirror=false" >> "$GITHUB_OUTPUT"
          fi

  mirror:
    name: Mirror repository to Epitech GitHub
    needs: [prerequisites]
    runs-on: ubuntu-latest
    if: ${{ needs.prerequisites.outputs.is_mirror_repository == 'false' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.REPOSITORY_URL }}
          ssh_private_key: ${{ secrets.REPOSITORY_SSH_PRIVATE_KEY }}
